blank_issues_enabled: false
contact_links:
  - name: "âœ¨ Feature ìš”ì²­"
    url: https://github.com/kok-server/issues/new?template=âœ…-feature.yml
    about: "ìƒˆë¡œìš´ ê¸°ëŠ¥ì„ ìš”ì²­í•˜ë ¤ë©´ í´ë¦­í•˜ì„¸ìš”."

  - name: "ğŸ› ï¸ Bug ìˆ˜ì • (Fix)"
    url: https://github.com/kok-server/issues/new?template=ğŸ”§-fix.yml
    about: "ë²„ê·¸ë¥¼ ìˆ˜ì •í•˜ë ¤ë©´ í´ë¦­í•˜ì„¸ìš”."

  - name: "ğŸ›« ë°°í¬ ê´€ë ¨ (Deploy)"
    url: https://github.com/kok-server/issues/new?template=ğŸ›«-deploy.yml
    about: "ë°°í¬ ê´€ë ¨ ì´ìŠˆë¥¼ ìƒì„±í•˜ë ¤ë©´ í´ë¦­í•˜ì„¸ìš”."

  - name: "ğŸ§¹ ê¸°íƒ€ ì‘ì—… (Chore)"
    url: https://github.com/kok-server/issues/new?template=ğŸ§¹-chore.yml
    about: "ê¸°íƒ€ ì‘ì—…(ë¬¸ì„œ ì •ë¦¬ ë“±)ì´ í•„ìš”í•  ê²½ìš° í´ë¦­í•˜ì„¸ìš”."

  - name: "ğŸš§ ì„¤ì • ê´€ë ¨ (Config)"
    url: https://github.com/kok-server/issues/new?template=ğŸš§-config.yml
    about: "ì„¤ì •ê´€ë ¨ ì´ìŠˆë¥¼ ìƒì„±í•˜ë ¤ë©´ ê²½ìš° í´ë¦­í•˜ì„¸ìš”."
