blank_issues_enabled: false
issue_templates:
  - name: "âœ¨ Feature ìš”ì²­"
    description: "ìƒˆë¡œìš´ ê¸°ëŠ¥ì„ ìš”ì²­í•˜ë ¤ë©´ í´ë¦­í•˜ì„¸ìš”."
    file: feature.yml

  - name: "ğŸ› ï¸ Bug ìˆ˜ì • (Fix)"
    description: "ë²„ê·¸ë¥¼ ìˆ˜ì •í•˜ë ¤ë©´ í´ë¦­í•˜ì„¸ìš”."
    file: fix.yml

  - name: "ğŸ›« ë°°í¬ ìš”ì²­ (Deploy)"
    description: "ë°°í¬ ê´€ë ¨ ì´ìŠˆë¥¼ ìƒì„±í•˜ë ¤ë©´ í´ë¦­í•˜ì„¸ìš”."
    file: deploy.yml

  - name: "ğŸ§¹ ê¸°íƒ€ ì‘ì—… (Chore)"
    description: "ê¸°íƒ€ ì‘ì—…(ë¬¸ì„œ ì •ë¦¬ ë“±ë“±..)ì´ í•„ìš”í•  ê²½ìš° í´ë¦­í•˜ì„¸ìš”."
    file: chore.yml
